___

# Python Review Exercises

This is a exercise to test your understanding of Python Basics.

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 8 to the power of 4?**

In [ ]:
8 ** 4

4096

In [52]:
pow(8, 4)

4096

** Split this string:**

    s = "Hi there John!"
    
**into a list. **

In [53]:
s = "Hi there John!"
lst = s.split()
print(lst)


['Hi', 'there', 'John!']


** Given the variables:**

    planet = "Moon"
    diameter = 3474

** Use .format() to print the following string: **

    The diameter of Moon is 3474 kilometers.

In [54]:
planet = "Moon"
diameter = 3474

In [63]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Moon is 3474 kilometers.


** Given this nested list, use indexing to grab the word "hello" **

In [64]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [72]:
word = lst[3][1][2][0]
print(word)

hello


** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **

In [73]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [80]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

** What is the main difference between a tuple and a list? **

In [81]:
# Tuple is immutable

** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**

In [88]:
def domainGet(email):
  return email.split('@')[1]

In [89]:
domainGet('user@domain.com')

'domain.com'

In [90]:
domainGet('user@domain.com')

'domain.com'

** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **

In [94]:
def findDog(s):
    return 'dog' in s.lower()

In [95]:
findDog('Is there a dog here?')

True

** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **

In [96]:
def countDog(s):
    return s.lower().split().count("dog")

In [97]:
countDog('This dog runs faster than the other dog dude!')

2

** Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**

    seq = ['soup','dog','salad','cat','great']

**should be filtered down to:**

    ['soup','salad']

In [99]:
seq = ['soup','dog','salad','cat','great']

In [100]:
list(filter(lambda w: w[0]=='s', seq))

['soup', 'salad']

['soup', 'salad']

### Final Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket".
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all
  cases. **

In [103]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speed -= 5
    
    if speed <= 60:
        return "No Ticket"
    elif speed <= 80:
        return "Small Ticket"
    else:
        return "Big Ticket"



In [104]:
caught_speeding(81,True)

'Small Ticket'

In [105]:
caught_speeding(81,False)

'Big Ticket'

In [106]:
caught_speeding(59,False)

'No Ticket'

In [107]:
for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


** Write a Python program to display only those numbers from a list that satisfy the following conditions

The number must be divisible by seven
If the number is greater than 210, then skip it and move to the following number
If the number is greater than 350, then stop the loop

In [108]:
numbers = [2, 17, 21, 35, 210, 211, 280, 310, 350, 360, 420]
for num in numbers:
    if num > 350:
        break          # Stop the loop completely
    if num > 210:
        continue       # Skip numbers greater than 210 (but <= 350)
    if num % 7 == 0:
        print(num)

21
35
210


** Print all prime numbers within a range

Note: A Prime Number is a number that cannot be made by multiplying other whole numbers. A prime number is a natural number greater than 1 that is not a product of two smaller natural numbers.

In [ ]:
start = 1
end = 100

print("Prime numbers between", start, "and", end, "are:")

for num in range(start, end + 1):
    if num > 1: 
        for i in range(2, int(num**0.5) + 1):  
            if num % i == 0:
                break
        else:
            print(num)

Prime numbers between 1 and 100 are:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


** Reverse a integer number
Given:

76542

Expected output:

24567

In [111]:
num = 76542

reversed_num = int(str(num)[::-1])

print(reversed_num)

24567


In [112]:
for i in range(1, 7):
    print(f"Current Number is : {i}  and the cube is {i**3}\n")

Current Number is : 1  and the cube is 1

Current Number is : 2  and the cube is 8

Current Number is : 3  and the cube is 27

Current Number is : 4  and the cube is 64

Current Number is : 5  and the cube is 125

Current Number is : 6  and the cube is 216



Current Number is : 1  and the cube is 1

Current Number is : 2  and the cube is 8

Current Number is : 3  and the cube is 27

Current Number is : 4  and the cube is 64

Current Number is : 5  and the cube is 125

Current Number is : 6  and the cube is 216


# Great job!